apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Use NodePort or ClusterIP if LoadBalancer is not needed
  ports:
  - port: 80
  selector:
    app: frontend
